"""Canonical CLI surface manifest for integration coverage."""

PUBLIC_TOP_LEVEL_FLAGS = {
    "-m", "--model",
    "-c", "--continue-chat",
    "-s", "--summarize",
    "-t", "--turns",
    "--delete-messages",
    "--delete-sessions",
    "--clean-session-research",
    "--all",
    "-H", "--history",
    "-pa", "--print-answer",
    "-ps", "--print-session",
    "-p", "--prompts",
    "-v", "--verbose",
    "-o", "--open",
    "-ss", "--sticky-session",
    "--config",
    "--session",
    "--tools",
    "-rs", "--resume-session",
    "-se", "-es", "--session-end",
    "-sh", "--session-history",
    "-r", "--research",
    "-sfm", "--session-from-message",
    "--reply",
    "-L", "--lean",
    "--shortlist",
    "-off", "-tool-off", "--tool-off",
    "--list-tools",
    "--query-corpus",
    "--query-corpus-max-sources",
    "--query-corpus-max-chunks",
    "--summarize-section",
    "--section-source",
    "--section-id",
    "--section-include-toc",
    "--section-detail",
    "--section-max-chunks",
    "--list-memories",
    "--delete-memory",
    "--clear-memories",
    "-em", "--elephant-mode",
    "-tl", "--terminal-lines",
    "-sp", "--system-prompt",
    "--completion-script",
}

GROUPED_COMMANDS = {
    "history list",
    "history show",
    "history delete",
    "session list",
    "session show",
    "session create",
    "session use",
    "session end",
    "session delete",
    "session clean-research",
    "session from-message",
    "memory list",
    "memory delete",
    "memory clear",
    "corpus query",
    "corpus summarize",
    "prompts list",
}

CONFIG_COMMANDS = {
    "config model add",
    "config model edit",
    "config daemon edit",
}

PERSONA_SUBCOMMANDS = {
    "persona create",
    "persona add-sources",
    "persona import",
    "persona export",
    "persona load",
    "persona unload",
    "persona current",
    "persona list",
    "persona alias",
    "persona unalias",
    "persona aliases",
    "persona ingest-book",
    "persona reingest-book",
    "persona books",
    "persona book-report",
    "persona viewpoints",
}

PLUGIN_FLAGS = {
    "--daemon",
    "--sendmail",
    "--subject",
    "--push-data",
    "--browser",
}

BEHAVIORAL_SURFACES = {
    "persona @mention",
    "persona alias mention",
}

HIDDEN_INTERNAL_FLAGS = {
    "--add-model": "--config model add",
    "--edit-model": "--config model edit",
    "-me": "--config model edit",
    "--from-message": "session from-message",
    "--tools-reset": "--tools reset",
    "--xmpp-daemon": "--daemon",
    "--edit-daemon": "--config daemon edit",
    "--xmpp-menubar-child": "--daemon",
}

COVERAGE_OWNERSHIP = {
    "-m": "test_cli_chat_controls_recorded.py",
    "--model": "test_cli_chat_controls_recorded.py",
    "-s": "test_cli_chat_controls_recorded.py",
    "--summarize": "test_cli_chat_controls_recorded.py",
    "-t": "test_cli_chat_controls_recorded.py",
    "--turns": "test_cli_chat_controls_recorded.py",
    "-v": "test_cli_chat_controls_recorded.py",
    "--verbose": "test_cli_chat_controls_recorded.py",
    "-o": "test_cli_chat_controls_recorded.py",
    "--open": "test_cli_chat_controls_recorded.py",
    "-L": "test_cli_chat_controls_recorded.py",
    "--lean": "test_cli_chat_controls_recorded.py",
    "--shortlist": "test_cli_chat_controls_recorded.py",
    "-off": "test_cli_chat_controls_recorded.py",
    "-tool-off": "test_cli_chat_controls_recorded.py",
    "--tool-off": "test_cli_chat_controls_recorded.py",
    "--list-tools": "test_cli_chat_controls_recorded.py",
    "--tools": "test_cli_chat_controls_recorded.py",
    "-tl": "test_cli_chat_controls_recorded.py",
    "--terminal-lines": "test_cli_chat_controls_recorded.py",
    "-sp": "test_cli_chat_controls_recorded.py",
    "--system-prompt": "test_cli_chat_controls_recorded.py",

    "--history": "test_cli_history_session_recorded.py",
    "-H": "test_cli_history_session_recorded.py",
    "-pa": "test_cli_history_session_recorded.py",
    "--print-answer": "test_cli_history_session_recorded.py",
    "history list": "test_cli_history_session_recorded.py",
    "history show": "test_cli_history_session_recorded.py",
    "history delete": "test_cli_history_session_recorded.py",
    "--delete-messages": "test_cli_history_session_recorded.py",
    "--delete-sessions": "test_cli_history_session_recorded.py",
    "--all": "test_cli_history_session_recorded.py",
    "--session-from-message": "test_cli_history_session_recorded.py",
    "-sfm": "test_cli_history_session_recorded.py",
    "session from-message": "test_cli_history_session_recorded.py",
    "--reply": "test_cli_history_session_recorded.py",
    "-c": "test_cli_history_session_recorded.py",
    "--continue-chat": "test_cli_history_session_recorded.py",
    "-p": "test_cli_history_session_recorded.py",
    "--prompts": "test_cli_history_session_recorded.py",
    "prompts list": "test_cli_history_session_recorded.py",

    "-ss": "test_cli_session_recorded.py",
    "--sticky-session": "test_cli_session_recorded.py",
    "--session": "test_cli_session_recorded.py",
    "-rs": "test_cli_session_recorded.py",
    "--resume-session": "test_cli_session_recorded.py",
    "-sh": "test_cli_session_recorded.py",
    "--session-history": "test_cli_session_recorded.py",
    "-ps": "test_cli_session_recorded.py",
    "--print-session": "test_cli_session_recorded.py",
    "-se": "test_cli_session_recorded.py",
    "-es": "test_cli_session_recorded.py",
    "--session-end": "test_cli_session_recorded.py",
    "--clean-session-research": "test_cli_session_recorded.py",
    "session list": "test_cli_session_recorded.py",
    "session show": "test_cli_session_recorded.py",
    "session create": "test_cli_session_recorded.py",
    "session use": "test_cli_session_recorded.py",
    "session end": "test_cli_session_recorded.py",
    "session delete": "test_cli_session_recorded.py",
    "session clean-research": "test_cli_session_recorded.py",

    "-r": "test_cli_research_local_recorded.py",
    "--research": "test_cli_research_local_recorded.py",
    "--query-corpus": "test_cli_research_local_recorded.py",
    "--query-corpus-max-sources": "test_cli_research_local_recorded.py",
    "--query-corpus-max-chunks": "test_cli_research_local_recorded.py",
    "--summarize-section": "test_cli_research_local_recorded.py",
    "--section-source": "test_cli_research_local_recorded.py",
    "--section-id": "test_cli_research_local_recorded.py",
    "--section-include-toc": "test_cli_research_local_recorded.py",
    "--section-detail": "test_cli_research_local_recorded.py",
    "--section-max-chunks": "test_cli_research_local_recorded.py",
    "corpus query": "test_cli_research_local_recorded.py",
    "corpus summarize": "test_cli_research_local_recorded.py",

    "--list-memories": "test_cli_memory_surface_recorded.py",
    "--delete-memory": "test_cli_memory_surface_recorded.py",
    "--clear-memories": "test_cli_memory_surface_recorded.py",
    "memory list": "test_cli_memory_surface_recorded.py",
    "memory delete": "test_cli_memory_surface_recorded.py",
    "memory clear": "test_cli_memory_surface_recorded.py",
    "-em": "test_cli_memory_surface_recorded.py",
    "--elephant-mode": "test_cli_memory_surface_recorded.py",

    "persona create": "test_cli_persona_recorded.py",
    "persona add-sources": "test_cli_persona_recorded.py",
    "persona import": "test_cli_persona_recorded.py",
    "persona export": "test_cli_persona_recorded.py",
    "persona load": "test_cli_persona_recorded.py",
    "persona unload": "test_cli_persona_recorded.py",
    "persona current": "test_cli_persona_recorded.py",
    "persona list": "test_cli_persona_recorded.py",
    "persona alias": "test_cli_persona_recorded.py",
    "persona unalias": "test_cli_persona_recorded.py",
    "persona aliases": "test_cli_persona_recorded.py",
    "persona ingest-book": "test_cli_persona_recorded.py",
    "persona reingest-book": "test_cli_persona_recorded.py",
    "persona books": "test_cli_persona_recorded.py",
    "persona book-report": "test_cli_persona_recorded.py",
    "persona viewpoints": "test_cli_persona_recorded.py",
    "persona @mention": "test_cli_persona_recorded.py",
    "persona alias mention": "test_cli_persona_recorded.py",

    "--daemon": "test_cli_plugin_surface_recorded.py",
    "--sendmail": "test_cli_plugin_surface_recorded.py",
    "--subject": "test_cli_plugin_surface_recorded.py",
    "--push-data": "test_cli_plugin_surface_recorded.py",
    "--browser": "test_cli_plugin_surface_recorded.py",

    "--config": "test_cli_interactive_subprocess.py",
    "config model add": "test_cli_interactive_subprocess.py",
    "config model edit": "test_cli_interactive_subprocess.py",
    "config daemon edit": "test_cli_interactive_subprocess.py",
    "--completion-script": "test_cli_interactive_subprocess.py",
}
